{{- with .Values.global }}
{{- if .useRegistryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-image-pull-secrets
  namespace: kubeflow
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-image-pull-secrets
  namespace: istio-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-image-pull-secrets
  namespace: kserve
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc -}}
{{ end -}}
{{ end -}}