{{ if and (.Values.enableIngress) (ne .Values.kubeflowHost "*") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ingress-thru-gateway
  namespace: istio-system
spec:
  {{ if .Values.tlsCrt }}
  tls:
  - hosts:
      - {{ .Values.kubeflowHost }}
    secretName: cpaas-https-certs
  {{ end }}
  rules:
  - host: {{ .Values.kubeflowHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
---
{{ if .Values.tlsCrt }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tlsCrt }}
  tls.key: {{ .Values.tlsKey }}
kind: Secret
metadata:
  name: cpaas-https-certs
  namespace: auth
type: kubernetes.io/tls
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-ingress-conf
  namespace: auth
spec:
  {{ if .Values.tlsCrt }}
  tls:
  - hosts:
      - {{ .Values.kubeflowHost }}
    secretName: cpaas-https-certs
  {{ end }}
  rules:
  - host: {{ .Values.kubeflowHost }}
    http:
      paths:
      - path: /dex
        pathType: Prefix
        backend:
          service:
            name: dex
            port:
              number: 5556
{{ end }}