apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    gateway-name: smm-ingressgateway-external
    gateway-type: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 81
      protocol: HTTP
