apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    gateway-name: kubeflow-ingressgateway
    gateway-type: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  labels:
    istio.io/rev: cp-v115x.istio-system
  name: kubeflow-ingressgateway
  namespace: kubeflow
spec:
  deployment:
    replicas:
      max: 1
      min: 1
  istioControlPlane:
    name: cp-v115x
    namespace: istio-system
  service:
    ports:
    - name: tcp-status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    type: LoadBalancer
  type: ingress
---
