apiVersion: v2
name: kubeflow
version: "1.6.2"
kubeVersion: ">=1.20.0"
description: |
  The Kubeflow project is dedicated to making deployments
  of machine learning (ML) workflows on Kubernetes simple,
  portable and scalable. Our goal is not to recreate other services,
  but to provide a straightforward way to deploy best-of-breed
  open-source systems for ML to diverse infrastructures.
  Anywhere you are running Kubernetes, you should be able to run Kubeflow.
type: application
keywords:
  - "Kubeflow"
  - "Kubernetes"
  - "machine learning"
  - "tensorflow"
  - "pytorch"
  - "XGBoost"
dependencies:
  - name: cert-manager
    version: "1.5.0"
    alias: cert-manager
    condition: cert-manager.enabled
  - name: dex
    version: "2.36.0"
    condition: dex.enabled
  - name: istio
    version: "1.14.1"
    condition: istio.enabled
  - name: knative-serving
    version: "1.9.2"
  - name: minio
    version: "1.0"
    condition: minio.enabled
