certManagerControllerImage: quay.io/jetstack/cert-manager-controller:v1.5.0
certManagerCAInjectorImage: quay.io/jetstack/cert-manager-cainjector:v1.5.0
certManagerWebHookImage: quay.io/jetstack/cert-manager-webhook:v1.5.0
